import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black px-6 py-12 text-white">
      <div className="mx-auto max-w-4xl">
        <p className="mb-4 text-sm font-semibold uppercase tracking-[0.25em] text-cyan-300">
          Legal
        </p>

        <h1 className="mb-4 text-4xl font-bold">Terms of Service</h1>

        <p className="mb-10 text-slate-400">Last updated: June 2026</p>

        <div className="space-y-6 text-slate-300">
          <section className="rounded-3xl border border-white/10 bg-slate-900/60 p-6">
            <h2 className="mb-2 text-2xl font-semibold text-white">
              Acceptance of Terms
            </h2>
            <p>
              By accessing or using CutMyShort, you agree to these Terms of
              Service. If you do not agree, you should not use the service.
            </p>
          </section>

          <section className="rounded-3xl border border-white/10 bg-slate-900/60 p-6">
            <h2 className="mb-2 text-2xl font-semibold text-white">
              Ownership of Content
            </h2>
            <p>
              You retain ownership of all videos, audio files, transcripts, and
              clips uploaded to or generated by CutMyShort. You are responsible
              for ensuring that you have the rights to upload, process, edit,
              and publish your content.
            </p>
          </section>

          <section className="rounded-3xl border border-white/10 bg-slate-900/60 p-6">
            <h2 className="mb-2 text-2xl font-semibold text-white">
              Uploaded Media
            </h2>
            <p>
              CutMyShort processes uploaded or linked media to generate
              short-form clips. Processing time may vary depending on file size,
              video length, server availability, and third-party services.
            </p>
          </section>

          <section className="rounded-3xl border border-white/10 bg-slate-900/60 p-6">
            <h2 className="mb-2 text-2xl font-semibold text-white">
              Prohibited Use
            </h2>
            <p>
              You may not use CutMyShort to upload, process, distribute, or
              create illegal, infringing, abusive, harmful, misleading,
              fraudulent, or unauthorized content.
            </p>
          </section>

          <section className="rounded-3xl border border-white/10 bg-slate-900/60 p-6">
            <h2 className="mb-2 text-2xl font-semibold text-white">
              Service Availability
            </h2>
            <p>
              We aim to provide reliable service, but we do not guarantee that
              CutMyShort will always be available, uninterrupted, secure, or
              error-free.
            </p>
          </section>

          <section className="rounded-3xl border border-white/10 bg-slate-900/60 p-6">
            <h2 className="mb-2 text-2xl font-semibold text-white">
              Limitation of Liability
            </h2>
            <p>
              CutMyShort is provided on an &quot;as-is&quot; and
              &quot;as-available&quot; basis. To the fullest extent permitted by
              law, we are not liable for indirect, incidental, consequential, or
              special damages arising from your use of the service.
            </p>
          </section>

          <section className="rounded-3xl border border-white/10 bg-slate-900/60 p-6">
            <h2 className="mb-2 text-2xl font-semibold text-white">
              Account Suspension or Termination
            </h2>
            <p>
              We may suspend or terminate access to CutMyShort if an account
              violates these terms, abuses the service, or creates security,
              legal, or operational risk.
            </p>
          </section>
        </div>

        <Link
          href="/"
          className="mt-10 inline-block rounded-2xl border border-white/10 px-5 py-3 text-cyan-400 hover:bg-white/10 hover:text-cyan-300"
        >
          ← Back to Home
        </Link>
      </div>
    </main>
  );
}